### ISSUE TITLE
No link to the actual Paper

### ISSUE THREAD

**Issue by slarrain** [jsajuria/bowling#1]
Hi,

Your Readme.md links to Google and not to your actual Paper.

I was interested.

Hope you can put a link to the paper!

Thanks,

Santiago.

**Comment by jsajuria** [comment]
Hi Santiago,

You are right, here is the published paper: http://apr.sagepub.com/content/early/2014/11/27/1532673X14557942.abstract

If you can't access it and need a copy of the pre-print paper, please send me an email to j.sajuria[at]ucl.ac.uk

Javier
